# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
